export const GET_CONFERENCE = "GET_CONFERENCE";
// export const REMOVE_CONFERENCE = 'REMOVE_CONFERENCE';
export const CONFERENCE_ERROR = "CONFERENCE_ERROR";
export const CREATE_CONFERENCE = "CREATE_CONFERENCE";
