export const LOAD_COUNTRYLIST = "LOAD_COUNTRYLIST";
export const LOAD_STATELIST = "LOAD_STATELIST";
export const LOAD_CITYLIST = "LOAD_CITYLIST";
export const LOAD_CREDIT_TYPES_LIST = "LOAD_CREDIT_TYPES_LIST";
