export const MYORGANIZATIONS_LOADED = "MYORGANIZATIONS_LOADED";
export const MYORGANIZATIONS_ERROR = "MYORGANIZATIONS_ERROR";
export const MYORGANIZATIONS_SELECTLIST_LOADED =
  "MYORGANIZATIONS_SELECTLIST_LOADED";
