import { utcToZonedTime, format } from 'date-fns-tz';
import enGB from 'date-fns/locale/en-GB';
import api from './api';
import StoreAndPersistStore from '../redux/store';
import { alertAction } from '../redux/alert/alertAction';
import {
  loadCountryListAction,
  loadStateListAction,
  loadCityListAction,
  loadCreditTypesListAction,
} from '../redux/list/listAction';

const { store } = StoreAndPersistStore;

export const getFormattedDateInTz = (date, timezone) => {
  let dateInTz;
  let formattedDate;

  if (date && timezone) {
    dateInTz = utcToZonedTime(date, timezone);
    formattedDate = format(dateInTz, 'MMM-dd-yyyy, HH:mm aa', {
      timeZone: timezone,
      locale: enGB,
    });
  } else {
    formattedDate = null;
  }
  return formattedDate;
};

export const getLocationString = (mode, city) => {
  let locationStrig = 'Location';
  if (mode?.length > 0) {
    if (mode?.includes('venue') && city) {
      locationStrig = city;
      // console.log("venue", locationStrig);
    }

    if (mode?.includes('onlineConf')) {
      locationStrig = 'Online';
      // console.log("online", locationStrig);
    }

    if (mode?.includes('venue') && mode?.includes('onlineConf')) {
      locationStrig = `${city} & Online`;
      // console.log("both", locationStrig);
    }
  }
  return locationStrig;
};

export const capitalize = (word) => {
  return word[0]?.toUpperCase() + word.slice(1).toLowerCase();
};

// get index for react-select components from value of key
// They array has to have value as one of the keys [{labe:"Some Lable", value:"Some Value"}]

export const getIndex = (myArray, valueOfKey) => {
  const index = myArray.map((object) => object.value).indexOf(valueOfKey);
  return index;
};

// get object for react-select components from value of key
// They array has to have value as one of the keys  [{labe:"Some Lable", value:"Some Value"}]

export const getOption = (myArray, valueOfKey) => {
  return myArray?.find((option) => option?.value === valueOfKey);
};

export const getValue = (options, value, isMulti) => {
  if (isMulti) {
    return value;
  } else {
    return options ? options?.find((option) => option.value === value) : '';
  }
};

export const loadLocations = async (searchText, callback) => {
  const response = await api.get(`venues/search?venue=${searchText}`);
  callback(response.data.data.venue);
};

export const loadCountryList = async () => {
  const url = `venues/countryList`;
  try {
    const response = await api.get(url);
    if (response) {
      store.dispatch(loadCountryListAction(response.data.data.countries));
      const { countries } = response.data.data;
      // if (editMode && practice?.country) {
      //   const Id = countries.find(
      //     (country) => country.label === practice?.country
      //   )?.countryId;
      //   loadStateList(Id);
      // }
    }
  } catch (err) {
    store.dispatch(alertAction(err.response.data.message, 'danger'));
  }
};

export const loadStateList = async (countryId) => {
  const url = `venues/stateList?countryId=${countryId}`;
  try {
    const response = await api.get(url);
    if (response) {
      store.dispatch(loadStateListAction(response.data.data.states));
    }
  } catch (err) {
    store.dispatch(alertAction(err.response.data.message, 'danger'));
  }
};

export const loadCityList = async (stateId) => {
  const url = `venues/cityList?stateId=${stateId}`;
  try {
    const response = await api.get(url);
    if (response) {
      store.dispatch(loadCityListAction(response.data.data.cities));
    }
  } catch (err) {
    store.dispatch(alertAction(err.response.data.message, 'danger'));
  }
};

export const loadCreditTypesList = async () => {
  const url = `common/conferences/credits`;
  try {
    const response = await api.get(url);
    if (response) {
      store.dispatch(loadCreditTypesListAction(response.data.data.credits));
    }
  } catch (err) {
    store.dispatch(alertAction(err.response.data.message, 'danger'));
  }
};

export const professions = [
  { value: 'physician', label: 'Physician' },
  { value: 'physicianAssistant', label: 'Physician Assistant' },
  { value: 'nursePractitioner', label: 'Nurse Practitioner' },
  { value: 'dentist', label: 'Dentist' },
  { value: 'nurse', label: 'Nurse' },
  { value: 'pharmacist', label: 'Pharmacist' },
  { value: 'physicalTherapist', label: 'Physical Therapist' },
  { value: 'occupationalTherapist', label: 'Occupational Therapist' },
  { value: 'speechTherapist', label: 'Speech Therapist' },
  { value: 'respiratoryTherapist', label: 'Respiratory Therapist' },
  { value: 'dietitian', label: 'Dietitian' },
  { value: 'socialWorker', label: 'Social Worker' },
  { value: 'caseManagement', label: 'Case Management' },
];

export const subspecialties = [
  { value: 'cardiology', label: 'Cardiology' },
  { value: 'intensivist', label: 'Intensivist' },
  { value: 'gastroenterologist', label: 'Gastroenterologist' },
  { value: 'dermatologist', label: 'Dermatologist' },
  { value: 'neurologist', label: 'Neurologist' },
  { value: 'hematologist', label: 'Hematologist' },
  { value: 'endodontist', label: 'Endodontist' },
  { value: 'orthodontist', label: 'Orthodontist' },
];

// length 164
export const currencylist = [
  { label: 'Afghan Afghani', value: 'AFA', symbol: '؋' },
  { label: 'Albanian Lek', value: 'ALL', symbol: 'Lek' },
  { label: 'Algerian Dinar', value: 'DZD', symbol: 'دج' },
  { label: 'Angolan Kwanza', value: 'AOA', symbol: 'Kz' },
  { label: 'Argentine Peso', value: 'ARS', symbol: '$' },
  { label: 'Armenian Dram', value: 'AMD', symbol: '֏' },
  { label: 'Aruban Florin', value: 'AWG', symbol: 'ƒ' },
  { label: 'Australian Dollar', value: 'AUD', symbol: '$' },
  { label: 'Azerbaijani Manat', value: 'AZN', symbol: 'm' },
  { label: 'Bahamian Dollar', value: 'BSD', symbol: 'B$' },
  { label: 'Bahraini Dinar', value: 'BHD', symbol: '.د.ب' },
  { label: 'Bangladeshi Taka', value: 'BDT', symbol: '৳' },
  { label: 'Barbadian Dollar', value: 'BBD', symbol: 'Bds$' },
  { label: 'Belarusian Ruble', value: 'BYR', symbol: 'Br' },
  { label: 'Belgian Franc', value: 'BEF', symbol: 'fr' },
  { label: 'Belize Dollar', value: 'BZD', symbol: '$' },
  { label: 'Bermudan Dollar', value: 'BMD', symbol: '$' },
  { label: 'Bhutanese Ngultrum', value: 'BTN', symbol: 'Nu.' },
  { label: 'Bitcoin', value: 'BTC', symbol: '฿' },
  { label: 'Bolivian Boliviano', value: 'BOB', symbol: 'Bs.' },
  {
    label: 'Bosnia-Herzegovina Convertible Mark',
    value: 'BAM',
    symbol: 'KM',
  },
  { label: 'Botswanan Pula', value: 'BWP', symbol: 'P' },
  { label: 'Brazilian Real', value: 'BRL', symbol: 'R$' },
  { label: 'British Pound Sterling', value: 'GBP', symbol: '£' },
  { label: 'Brunei Dollar', value: 'BND', symbol: 'B$' },
  { label: 'Bulgarian Lev', value: 'BGN', symbol: 'Лв.' },
  { label: 'Burundian Franc', value: 'BIF', symbol: 'FBu' },
  { label: 'Cambodian Riel', value: 'KHR', symbol: 'KHR' },
  { label: 'Canadian Dollar', value: 'CAD', symbol: '$' },
  { label: 'Cape Verdean Escudo', value: 'CVE', symbol: '$' },
  { label: 'Cayman Islands Dollar', value: 'KYD', symbol: '$' },
  { label: 'CFA Franc BCEAO', value: 'XOF', symbol: 'CFA' },
  { label: 'CFA Franc BEAC', value: 'XAF', symbol: 'FCFA' },
  { label: 'CFP Franc', value: 'XPF', symbol: '₣' },
  { label: 'Chilean Peso', value: 'CLP', symbol: '$' },
  { label: 'Chinese Yuan', value: 'CNY', symbol: '¥' },
  { label: 'Colombian Peso', value: 'COP', symbol: '$' },
  { label: 'Comorian Franc', value: 'KMF', symbol: 'CF' },
  { label: 'Congolese Franc', value: 'CDF', symbol: 'FC' },
  { label: 'Costa Rican ColÃ³n', value: 'CRC', symbol: '₡' },
  { label: 'Croatian Kuna', value: 'HRK', symbol: 'kn' },
  { label: 'Cuban Convertible Peso', value: 'CUC', symbol: '$, CUC' },
  { label: 'Czech Republic Koruna', value: 'CZK', symbol: 'Kč' },
  { label: 'Danish Krone', value: 'DKK', symbol: 'Kr.' },
  { label: 'Djiboutian Franc', value: 'DJF', symbol: 'Fdj' },
  { label: 'Dominican Peso', value: 'DOP', symbol: '$' },
  { label: 'East Caribbean Dollar', value: 'XCD', symbol: '$' },
  { label: 'Egyptian Pound', value: 'EGP', symbol: 'ج.م' },
  { label: 'Eritrean Nakfa', value: 'ERN', symbol: 'Nfk' },
  { label: 'Estonian Kroon', value: 'EEK', symbol: 'kr' },
  { label: 'Ethiopian Birr', value: 'ETB', symbol: 'Nkf' },
  { label: 'Euro', value: 'EUR', symbol: '€' },
  { label: 'Falkland Islands Pound', value: 'FKP', symbol: '£' },
  { label: 'Fijian Dollar', value: 'FJD', symbol: 'FJ$' },
  { label: 'Gambian Dalasi', value: 'GMD', symbol: 'D' },
  { label: 'Georgian Lari', value: 'GEL', symbol: 'ლ' },
  { label: 'German Mark', value: 'DEM', symbol: 'DM' },
  { label: 'Ghanaian Cedi', value: 'GHS', symbol: 'GH₵' },
  { label: 'Gibraltar Pound', value: 'GIP', symbol: '£' },
  { label: 'Greek Drachma', value: 'GRD', symbol: '₯, Δρχ, Δρ' },
  { label: 'Guatemalan Quetzal', value: 'GTQ', symbol: 'Q' },
  { label: 'Guinean Franc', value: 'GNF', symbol: 'FG' },
  { label: 'Guyanaese Dollar', value: 'GYD', symbol: '$' },
  { label: 'Haitian Gourde', value: 'HTG', symbol: 'G' },
  { label: 'Honduran Lempira', value: 'HNL', symbol: 'L' },
  { label: 'Hong Kong Dollar', value: 'HKD', symbol: '$' },
  { label: 'Hungarian Forint', value: 'HUF', symbol: 'Ft' },
  { label: 'Icelandic KrÃ³na', value: 'ISK', symbol: 'kr' },
  { label: 'Indian Rupee - INR (₹) ', value: 'INR', symbol: '₹' },
  { label: 'Indonesian Rupiah', value: 'IDR', symbol: 'Rp' },
  { label: 'Iranian Rial', value: 'IRR', symbol: '﷼' },
  { label: 'Iraqi Dinar', value: 'IQD', symbol: 'د.ع' },
  { label: 'Israeli New Sheqel', value: 'ILS', symbol: '₪' },
  { label: 'Italian Lira', value: 'ITL', symbol: 'L,£' },
  { label: 'Jamaican Dollar', value: 'JMD', symbol: 'J$' },
  { label: 'Japanese Yen', value: 'JPY', symbol: '¥' },
  { label: 'Jordanian Dinar', value: 'JOD', symbol: 'ا.د' },
  { label: 'Kazakhstani Tenge', value: 'KZT', symbol: 'лв' },
  { label: 'Kenyan Shilling', value: 'KES', symbol: 'KSh' },
  { label: 'Kuwaiti Dinar', value: 'KWD', symbol: 'ك.د' },
  { label: 'Kyrgystani Som', value: 'KGS', symbol: 'лв' },
  { label: 'Laotian Kip', value: 'LAK', symbol: '₭' },
  { label: 'Latvian Lats', value: 'LVL', symbol: 'Ls' },
  { label: 'Lebanese Pound', value: 'LBP', symbol: '£' },
  { label: 'Lesotho Loti', value: 'LSL', symbol: 'L' },
  { label: 'Liberian Dollar', value: 'LRD', symbol: '$' },
  { label: 'Libyan Dinar', value: 'LYD', symbol: 'د.ل' },
  { label: 'Lithuanian Litas', value: 'LTL', symbol: 'Lt' },
  { label: 'Macanese Pataca', value: 'MOP', symbol: '$' },
  { label: 'Macedonian Denar', value: 'MKD', symbol: 'ден' },
  { label: 'Malagasy Ariary', value: 'MGA', symbol: 'Ar' },
  { label: 'Malawian Kwacha', value: 'MWK', symbol: 'MK' },
  { label: 'Malaysian Ringgit', value: 'MYR', symbol: 'RM' },
  { label: 'Maldivian Rufiyaa', value: 'MVR', symbol: 'Rf' },
  { label: 'Mauritanian Ouguiya', value: 'MRO', symbol: 'MRU' },
  { label: 'Mauritian Rupee', value: 'MUR', symbol: '₨' },
  { label: 'Mexican Peso', value: 'MXN', symbol: '$' },
  { label: 'Moldovan Leu', value: 'MDL', symbol: 'L' },
  { label: 'Mongolian Tugrik', value: 'MNT', symbol: '₮' },
  { label: 'Moroccan Dirham', value: 'MAD', symbol: 'MAD' },
  { label: 'Mozambican Metical', value: 'MZM', symbol: 'MT' },
  { label: 'Myanmar Kyat', value: 'MMK', symbol: 'K' },
  { label: 'Namibian Dollar', value: 'NAD', symbol: '$' },
  { label: 'Nepalese Rupee', value: 'NPR', symbol: '₨' },
  {
    label: 'Netherlands Antillean Guilder',
    value: 'ANG',
    symbol: 'ƒ',
  },
  { label: 'New Taiwan Dollar', value: 'TWD', symbol: '$' },
  { label: 'New Zealand Dollar', value: 'NZD', symbol: '$' },
  { label: 'Nicaraguan CÃ³rdoba', value: 'NIO', symbol: 'C$' },
  { label: 'Nigerian Naira', value: 'NGN', symbol: '₦' },
  { label: 'North Korean Won', value: 'KPW', symbol: '₩' },
  { label: 'Norwegian Krone', value: 'NOK', symbol: 'kr' },
  { label: 'Omani Rial', value: 'OMR', symbol: '.ع.ر' },
  { label: 'Pakistani Rupee', value: 'PKR', symbol: '₨' },
  { label: 'Panamanian Balboa', value: 'PAB', symbol: 'B/.' },
  { label: 'Papua New Guinean Kina', value: 'PGK', symbol: 'K' },
  { label: 'Paraguayan Guarani', value: 'PYG', symbol: '₲' },
  { label: 'Peruvian Nuevo Sol', value: 'PEN', symbol: 'S/.' },
  { label: 'Philippine Peso', value: 'PHP', symbol: '₱' },
  { label: 'Polish Zloty', value: 'PLN', symbol: 'zł' },
  { label: 'Qatari Rial', value: 'QAR', symbol: 'ق.ر' },
  { label: 'Romanian Leu', value: 'RON', symbol: 'lei' },
  { label: 'Russian Ruble', value: 'RUB', symbol: '₽' },
  { label: 'Rwandan Franc', value: 'RWF', symbol: 'FRw' },
  { label: 'Salvadoran ColÃ³n', value: 'SVC', symbol: '₡' },
  { label: 'Samoan Tala', value: 'WST', symbol: 'SAT' },
  { label: 'Saudi Riyal', value: 'SAR', symbol: '﷼' },
  { label: 'Serbian Dinar', value: 'RSD', symbol: 'din' },
  { label: 'Seychellois Rupee', value: 'SCR', symbol: 'SRe' },
  { label: 'Sierra Leonean Leone', value: 'SLL', symbol: 'Le' },
  { label: 'Singapore Dollar', value: 'SGD', symbol: '$' },
  { label: 'Slovak Koruna', value: 'SKK', symbol: 'Sk' },
  { label: 'Solomon Islands Dollar', value: 'SBD', symbol: 'Si$' },
  { label: 'Somali Shilling', value: 'SOS', symbol: 'Sh.so.' },
  { label: 'South African Rand', value: 'ZAR', symbol: 'R' },
  { label: 'South Korean Won', value: 'KRW', symbol: '₩' },
  { label: 'Special Drawing Rights', value: 'XDR', symbol: 'SDR' },
  { label: 'Sri Lankan Rupee', value: 'LKR', symbol: 'Rs' },
  { label: 'St. Helena Pound', value: 'SHP', symbol: '£' },
  { label: 'Sudanese Pound', value: 'SDG', symbol: '.س.ج' },
  { label: 'Surinamese Dollar', value: 'SRD', symbol: '$' },
  { label: 'Swazi Lilangeni', value: 'SZL', symbol: 'E' },
  { label: 'Swedish Krona', value: 'SEK', symbol: 'kr' },
  { label: 'Swiss Franc', value: 'CHF', symbol: 'CHf' },
  { label: 'Syrian Pound', value: 'SYP', symbol: 'LS' },
  { label: 'São Tomé and Príncipe Dobra', value: 'STD', symbol: 'Db' },
  { label: 'Tajikistani Somoni', value: 'TJS', symbol: 'SM' },
  { label: 'Tanzanian Shilling', value: 'TZS', symbol: 'TSh' },
  { label: 'Thai Baht', value: 'THB', symbol: '฿' },
  { label: "Tongan Pa'anga", value: 'TOP', symbol: '$' },
  { label: 'Trinidad & Tobago Dollar', value: 'TTD', symbol: '$' },
  { label: 'Tunisian Dinar', value: 'TND', symbol: 'ت.د' },
  { label: 'Turkish Lira', value: 'TRY', symbol: '₺' },
  { label: 'Turkmenistani Manat', value: 'TMT', symbol: 'T' },
  { label: 'Ugandan Shilling', value: 'UGX', symbol: 'USh' },
  { label: 'Ukrainian Hryvnia', value: 'UAH', symbol: '₴' },
  {
    label: 'United Arab Emirates Dirham',
    value: 'AED',
    symbol: 'إ.د',
  },
  { label: 'Uruguayan Peso', value: 'UYU', symbol: '$' },
  { label: 'US Dollar', value: 'USD', symbol: '$' },
  { label: 'Uzbekistan Som', value: 'UZS', symbol: 'лв' },
  { label: 'Vanuatu Vatu', value: 'VUV', symbol: 'VT' },
  { label: 'Venezuelan BolÃvar', value: 'VEF', symbol: 'Bs' },
  { label: 'Vietnamese Dong', value: 'VND', symbol: '₫' },
  { label: 'Yemeni Rial', value: 'YER', symbol: '﷼' },
  { label: 'Zambian Kwacha', value: 'ZMK', symbol: 'ZK' },
];

// export const timezones = [
//   {
//     value: "(UTC-12:00) International Date Line West",
//     label: "(UTC-12:00) International Date Line West",
//   },
//   {
//     value: "(UTC-11:00) Coordinated Universal Time-11",
//     label: "(UTC-11:00) Coordinated Universal Time-11",
//   },
//   { value: "(UTC-10:00) Hawaii", label: "(UTC-10:00) Hawaii" },
//   { value: "(UTC-09:00) Alaska", label: "(UTC-09:00) Alaska" },
//   {
//     value: "(UTC-08:00) Baja California",
//     label: "(UTC-08:00) Baja California",
//   },
//   {
//     value: "(UTC-08:00) Pacific Time (US and Canada)",
//     label: "(UTC-08:00) Pacific Time (US and Canada)",
//   },
//   {
//     value: "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
//     label: "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
//   },
//   { value: "(UTC-07:00) Arizona", label: "(UTC-07:00) Arizona" },
//   {
//     value: "(UTC-07:00) Mountain Time (US and Canada)",
//     label: "(UTC-07:00) Mountain Time (US and Canada)",
//   },
//   {
//     value: "(UTC-06:00) Central America",
//     label: "(UTC-06:00) Central America",
//   },
//   {
//     value: "(UTC-06:00) Central Time (US and Canada)",
//     label: "(UTC-06:00) Central Time (US and Canada)",
//   },
//   { value: "(UTC-06:00) Saskatchewan", label: "(UTC-06:00) Saskatchewan" },
//   {
//     value: "(UTC-06:00) Guadalajara, Mexico City, Monterey",
//     label: "(UTC-06:00) Guadalajara, Mexico City, Monterey",
//   },
//   {
//     value: "(UTC-05:00) Bogota, Lima, Quito",
//     label: "(UTC-05:00) Bogota, Lima, Quito",
//   },
//   {
//     value: "(UTC-05:00) Indiana (East)",
//     label: "(UTC-05:00) Indiana (East)",
//   },
//   {
//     value: "(UTC-05:00) Eastern Time (US and Canada)",
//     label: "(UTC-05:00) Eastern Time (US and Canada)",
//   },
//   { value: "(UTC-04:30) Caracas", label: "(UTC-04:30) Caracas" },
//   {
//     value: "(UTC-04:00) Atlantic Time (Canada)",
//     label: "(UTC-04:00) Atlantic Time (Canada)",
//   },
//   { value: "(UTC-04:00) Asuncion", label: "(UTC-04:00) Asuncion" },
//   {
//     value: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
//     label: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
//   },
//   { value: "(UTC-04:00) Cuiaba", label: "(UTC-04:00) Cuiaba" },
//   { value: "(UTC-04:00) Santiago", label: "(UTC-04:00) Santiago" },
//   { value: "(UTC-03:30) Newfoundland", label: "(UTC-03:30) Newfoundland" },
//   { value: "(UTC-03:00) Brasilia", label: "(UTC-03:00) Brasilia" },
//   { value: "(UTC-03:00) Greenland", label: "(UTC-03:00) Greenland" },
//   {
//     value: "(UTC-03:00) Cayenne, Fortaleza",
//     label: "(UTC-03:00) Cayenne, Fortaleza",
//   },
//   { value: "(UTC-03:00) Buenos Aires", label: "(UTC-03:00) Buenos Aires" },
//   { value: "(UTC-03:00) Montevideo", label: "(UTC-03:00) Montevideo" },
//   {
//     value: "(UTC-02:00) Coordinated Universal Time-2",
//     label: "(UTC-02:00) Coordinated Universal Time-2",
//   },
//   { value: "(UTC-01:00) Cape Verde", label: "(UTC-01:00) Cape Verde" },
//   { value: "(UTC-01:00) Azores", label: "(UTC-01:00) Azores" },
//   { value: "(UTC+00:00) Casablanca", label: "(UTC+00:00) Casablanca" },
//   {
//     value: "(UTC+00:00) Monrovia, Reykjavik",
//     label: "(UTC+00:00) Monrovia, Reykjavik",
//   },
//   {
//     value: "(UTC+00:00) Dublin, Edinburgh, Lisbon, London",
//     label: "(UTC+00:00) Dublin, Edinburgh, Lisbon, London",
//   },
//   {
//     value: "(UTC+00:00) Coordinated Universal Time",
//     label: "(UTC+00:00) Coordinated Universal Time",
//   },
//   {
//     value: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
//     label: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
//   },
//   {
//     value: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
//     label: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
//   },
//   {
//     value: "(UTC+01:00) West Central Africa",
//     label: "(UTC+01:00) West Central Africa",
//   },
//   {
//     value: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
//     label: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
//   },
//   {
//     value: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
//     label: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
//   },
//   { value: "(UTC+01:00) Windhoek", label: "(UTC+01:00) Windhoek" },
//   {
//     value: "(UTC+02:00) Athens, Bucharest, Istanbul",
//     label: "(UTC+02:00) Athens, Bucharest, Istanbul",
//   },
//   {
//     value: "(UTC+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
//     label: "(UTC+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
//   },
//   { value: "(UTC+02:00) Cairo", label: "(UTC+02:00) Cairo" },
//   { value: "(UTC+02:00) Damascus", label: "(UTC+02:00) Damascus" },
//   { value: "(UTC+02:00) Amman", label: "(UTC+02:00) Amman" },
//   {
//     value: "(UTC+02:00) Harare, Pretoria",
//     label: "(UTC+02:00) Harare, Pretoria",
//   },
//   { value: "(UTC+02:00) Jerusalem", label: "(UTC+02:00) Jerusalem" },
//   { value: "(UTC+02:00) Beirut", label: "(UTC+02:00) Beirut" },
//   { value: "(UTC+03:00) Baghdad", label: "(UTC+03:00) Baghdad" },
//   { value: "(UTC+03:00) Minsk", label: "(UTC+03:00) Minsk" },
//   {
//     value: "(UTC+03:00) Kuwait, Riyadh",
//     label: "(UTC+03:00) Kuwait, Riyadh",
//   },
//   { value: "(UTC+03:00) Nairobi", label: "(UTC+03:00) Nairobi" },
//   { value: "(UTC+03:30) Tehran", label: "(UTC+03:30) Tehran" },
//   {
//     value: "(UTC+04:00) Moscow, St. Petersburg, Volgograd",
//     label: "(UTC+04:00) Moscow, St. Petersburg, Volgograd",
//   },
//   { value: "(UTC+04:00) Tbilisi", label: "(UTC+04:00) Tbilisi" },
//   { value: "(UTC+04:00) Yerevan", label: "(UTC+04:00) Yerevan" },
//   {
//     value: "(UTC+04:00) Abu Dhabi, Muscat",
//     label: "(UTC+04:00) Abu Dhabi, Muscat",
//   },
//   { value: "(UTC+04:00) Baku", label: "(UTC+04:00) Baku" },
//   { value: "(UTC+04:00) Port Louis", label: "(UTC+04:00) Port Louis" },
//   { value: "(UTC+04:30) Kabul", label: "(UTC+04:30) Kabul" },
//   { value: "(UTC+05:00) Tashkent", label: "(UTC+05:00) Tashkent" },
//   {
//     value: "(UTC+05:00) Islamabad, Karachi",
//     label: "(UTC+05:00) Islamabad, Karachi",
//   },
//   {
//     value: "(UTC+05:30) Sri Jayewardenepura Kotte",
//     label: "(UTC+05:30) Sri Jayewardenepura Kotte",
//   },
//   {
//     value: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
//     label: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
//   },
//   { value: "(UTC+05:45) Kathmandu", label: "(UTC+05:45) Kathmandu" },
//   { value: "(UTC+06:00) Astana", label: "(UTC+06:00) Astana" },
//   { value: "(UTC+06:00) Dhaka", label: "(UTC+06:00) Dhaka" },
//   { value: "(UTC+06:00) Yekaterinburg", label: "(UTC+06:00) Yekaterinburg" },
//   { value: "(UTC+06:30) Yangon", label: "(UTC+06:30) Yangon" },
//   {
//     value: "(UTC+07:00) Bangkok, Hanoi, Jakarta",
//     label: "(UTC+07:00) Bangkok, Hanoi, Jakarta",
//   },
//   { value: "(UTC+07:00) Novosibirsk", label: "(UTC+07:00) Novosibirsk" },
//   { value: "(UTC+08:00) Krasnoyarsk", label: "(UTC+08:00) Krasnoyarsk" },
//   { value: "(UTC+08:00) Ulaanbaatar", label: "(UTC+08:00) Ulaanbaatar" },
//   {
//     value: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
//     label: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
//   },
//   { value: "(UTC+08:00) Perth", label: "(UTC+08:00) Perth" },
//   {
//     value: "(UTC+08:00) Kuala Lumpur, Singapore",
//     label: "(UTC+08:00) Kuala Lumpur, Singapore",
//   },
//   { value: "(UTC+08:00) Taipei", label: "(UTC+08:00) Taipei" },
//   { value: "(UTC+09:00) Irkutsk", label: "(UTC+09:00) Irkutsk" },
//   { value: "(UTC+09:00) Seoul", label: "(UTC+09:00) Seoul" },
//   {
//     value: "(UTC+09:00) Osaka, Sapporo, Tokyo",
//     label: "(UTC+09:00) Osaka, Sapporo, Tokyo",
//   },
//   { value: "(UTC+09:30) Darwin", label: "(UTC+09:30) Darwin" },
//   { value: "(UTC+09:30) Adelaide", label: "(UTC+09:30) Adelaide" },
//   { value: "(UTC+10:00) Hobart", label: "(UTC+10:00) Hobart" },
//   { value: "(UTC+10:00) Yakutsk", label: "(UTC+10:00) Yakutsk" },
//   { value: "(UTC+10:00) Brisbane", label: "(UTC+10:00) Brisbane" },
//   {
//     value: "(UTC+10:00) Guam, Port Moresby",
//     label: "(UTC+10:00) Guam, Port Moresby",
//   },
//   {
//     value: "(UTC+10:00) Canberra, Melbourne, Sydney",
//     label: "(UTC+10:00) Canberra, Melbourne, Sydney",
//   },
//   { value: "(UTC+11:00) Vladivostok", label: "(UTC+11:00) Vladivostok" },
//   {
//     value: "(UTC+11:00) Solomon Islands, New Caledonia",
//     label: "(UTC+11:00) Solomon Islands, New Caledonia",
//   },
//   {
//     value: "(UTC+12:00) Coordinated Universal Time+12",
//     label: "(UTC+12:00) Coordinated Universal Time+12",
//   },
//   {
//     value: "(UTC+12:00) Fiji, Marshall Islands",
//     label: "(UTC+12:00) Fiji, Marshall Islands",
//   },
//   { value: "(UTC+12:00) Magadan", label: "(UTC+12:00) Magadan" },
//   {
//     value: "(UTC+12:00) Auckland, Wellington",
//     label: "(UTC+12:00) Auckland, Wellington",
//   },
//   { value: "(UTC+13:00) Nuku'alofa", label: "(UTC+13:00) Nuku'alofa" },
//   { value: "(UTC+13:00) Samoa", label: "(UTC+13:00) Samoa" },
// ];

export const timezones = [
  { value: 'Africa/Abidjan', label: 'Africa/Abidjan' },
  { value: 'Africa/Accra', label: 'Africa/Accra' },
  { value: 'Africa/Addis_Ababa', label: 'Africa/Addis_Ababa' },
  { value: 'Africa/Algiers', label: 'Africa/Algiers' },
  { value: 'Africa/Asmara', label: 'Africa/Asmara' },
  { value: 'Africa/Asmera', label: 'Africa/Asmera' },
  { value: 'Africa/Bamako', label: 'Africa/Bamako' },
  { value: 'Africa/Bangui', label: 'Africa/Bangui' },
  { value: 'Africa/Banjul', label: 'Africa/Banjul' },
  { value: 'Africa/Bissau', label: 'Africa/Bissau' },
  { value: 'Africa/Blantyre', label: 'Africa/Blantyre' },
  { value: 'Africa/Brazzaville', label: 'Africa/Brazzaville' },
  { value: 'Africa/Bujumbura', label: 'Africa/Bujumbura' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo' },
  { value: 'Africa/Casablanca', label: 'Africa/Casablanca' },
  { value: 'Africa/Ceuta', label: 'Africa/Ceuta' },
  { value: 'Africa/Conakry', label: 'Africa/Conakry' },
  { value: 'Africa/Dakar', label: 'Africa/Dakar' },
  { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar_es_Salaam' },
  { value: 'Africa/Djibouti', label: 'Africa/Djibouti' },
  { value: 'Africa/Douala', label: 'Africa/Douala' },
  { value: 'Africa/El_Aaiun', label: 'Africa/El_Aaiun' },
  { value: 'Africa/Freetown', label: 'Africa/Freetown' },
  { value: 'Africa/Gaborone', label: 'Africa/Gaborone' },
  { value: 'Africa/Harare', label: 'Africa/Harare' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg' },
  { value: 'Africa/Juba', label: 'Africa/Juba' },
  { value: 'Africa/Kampala', label: 'Africa/Kampala' },
  { value: 'Africa/Khartoum', label: 'Africa/Khartoum' },
  { value: 'Africa/Kigali', label: 'Africa/Kigali' },
  { value: 'Africa/Kinshasa', label: 'Africa/Kinshasa' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos' },
  { value: 'Africa/Libreville', label: 'Africa/Libreville' },
  { value: 'Africa/Lome', label: 'Africa/Lome' },
  { value: 'Africa/Luanda', label: 'Africa/Luanda' },
  { value: 'Africa/Lubumbashi', label: 'Africa/Lubumbashi' },
  { value: 'Africa/Lusaka', label: 'Africa/Lusaka' },
  { value: 'Africa/Malabo', label: 'Africa/Malabo' },
  { value: 'Africa/Maputo', label: 'Africa/Maputo' },
  { value: 'Africa/Maseru', label: 'Africa/Maseru' },
  { value: 'Africa/Mbabane', label: 'Africa/Mbabane' },
  { value: 'Africa/Mogadishu', label: 'Africa/Mogadishu' },
  { value: 'Africa/Monrovia', label: 'Africa/Monrovia' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi' },
  { value: 'Africa/Ndjamena', label: 'Africa/Ndjamena' },
  { value: 'Africa/Niamey', label: 'Africa/Niamey' },
  { value: 'Africa/Nouakchott', label: 'Africa/Nouakchott' },
  { value: 'Africa/Ouagadougou', label: 'Africa/Ouagadougou' },
  { value: 'Africa/Porto-Novo', label: 'Africa/Porto-Novo' },
  { value: 'Africa/Sao_Tome', label: 'Africa/Sao_Tome' },
  { value: 'Africa/Timbuktu', label: 'Africa/Timbuktu' },
  { value: 'Africa/Tripoli', label: 'Africa/Tripoli' },
  { value: 'Africa/Tunis', label: 'Africa/Tunis' },
  { value: 'Africa/Windhoek', label: 'Africa/Windhoek' },
  { value: 'America/Adak', label: 'America/Adak' },
  { value: 'America/Anchorage', label: 'America/Anchorage' },
  { value: 'America/Anguilla', label: 'America/Anguilla' },
  { value: 'America/Antigua', label: 'America/Antigua' },
  { value: 'America/Araguaina', label: 'America/Araguaina' },
  {
    value: 'America/Argentina/Buenos_Aires',
    label: 'America/Argentina/Buenos_Aires',
  },
  {
    value: 'America/Argentina/Catamarca',
    label: 'America/Argentina/Catamarca',
  },
  {
    value: 'America/Argentina/ComodRivadavia',
    label: 'America/Argentina/ComodRivadavia',
  },
  { value: 'America/Argentina/Cordoba', label: 'America/Argentina/Cordoba' },
  { value: 'America/Argentina/Jujuy', label: 'America/Argentina/Jujuy' },
  { value: 'America/Argentina/La_Rioja', label: 'America/Argentina/La_Rioja' },
  { value: 'America/Argentina/Mendoza', label: 'America/Argentina/Mendoza' },
  {
    value: 'America/Argentina/Rio_Gallegos',
    label: 'America/Argentina/Rio_Gallegos',
  },
  { value: 'America/Argentina/Salta', label: 'America/Argentina/Salta' },
  { value: 'America/Argentina/San_Juan', label: 'America/Argentina/San_Juan' },
  { value: 'America/Argentina/San_Luis', label: 'America/Argentina/San_Luis' },
  { value: 'America/Argentina/Tucuman', label: 'America/Argentina/Tucuman' },
  { value: 'America/Argentina/Ushuaia', label: 'America/Argentina/Ushuaia' },
  { value: 'America/Aruba', label: 'America/Aruba' },
  { value: 'America/Asuncion', label: 'America/Asuncion' },
  { value: 'America/Atikokan', label: 'America/Atikokan' },
  { value: 'America/Atka', label: 'America/Atka' },
  { value: 'America/Bahia', label: 'America/Bahia' },
  { value: 'America/Bahia_Banderas', label: 'America/Bahia_Banderas' },
  { value: 'America/Barbados', label: 'America/Barbados' },
  { value: 'America/Belem', label: 'America/Belem' },
  { value: 'America/Belize', label: 'America/Belize' },
  { value: 'America/Blanc-Sablon', label: 'America/Blanc-Sablon' },
  { value: 'America/Boa_Vista', label: 'America/Boa_Vista' },
  { value: 'America/Bogota', label: 'America/Bogota' },
  { value: 'America/Boise', label: 'America/Boise' },
  { value: 'America/Buenos_Aires', label: 'America/Buenos_Aires' },
  { value: 'America/Cambridge_Bay', label: 'America/Cambridge_Bay' },
  { value: 'America/Campo_Grande', label: 'America/Campo_Grande' },
  { value: 'America/Cancun', label: 'America/Cancun' },
  { value: 'America/Caracas', label: 'America/Caracas' },
  { value: 'America/Catamarca', label: 'America/Catamarca' },
  { value: 'America/Cayenne', label: 'America/Cayenne' },
  { value: 'America/Cayman', label: 'America/Cayman' },
  { value: 'America/Chicago', label: 'America/Chicago' },
  { value: 'America/Chihuahua', label: 'America/Chihuahua' },
  { value: 'America/Coral_Harbour', label: 'America/Coral_Harbour' },
  { value: 'America/Cordoba', label: 'America/Cordoba' },
  { value: 'America/Costa_Rica', label: 'America/Costa_Rica' },
  { value: 'America/Creston', label: 'America/Creston' },
  { value: 'America/Cuiaba', label: 'America/Cuiaba' },
  { value: 'America/Curacao', label: 'America/Curacao' },
  { value: 'America/Danmarkshavn', label: 'America/Danmarkshavn' },
  { value: 'America/Dawson', label: 'America/Dawson' },
  { value: 'America/Dawson_Creek', label: 'America/Dawson_Creek' },
  { value: 'America/Denver', label: 'America/Denver' },
  { value: 'America/Detroit', label: 'America/Detroit' },
  { value: 'America/Dominica', label: 'America/Dominica' },
  { value: 'America/Edmonton', label: 'America/Edmonton' },
  { value: 'America/Eirunepe', label: 'America/Eirunepe' },
  { value: 'America/El_Salvador', label: 'America/El_Salvador' },
  { value: 'America/Ensenada', label: 'America/Ensenada' },
  { value: 'America/Fort_Nelson', label: 'America/Fort_Nelson' },
  { value: 'America/Fort_Wayne', label: 'America/Fort_Wayne' },
  { value: 'America/Fortaleza', label: 'America/Fortaleza' },
  { value: 'America/Glace_Bay', label: 'America/Glace_Bay' },
  { value: 'America/Godthab', label: 'America/Godthab' },
  { value: 'America/Goose_Bay', label: 'America/Goose_Bay' },
  { value: 'America/Grand_Turk', label: 'America/Grand_Turk' },
  { value: 'America/Grenada', label: 'America/Grenada' },
  { value: 'America/Guadeloupe', label: 'America/Guadeloupe' },
  { value: 'America/Guatemala', label: 'America/Guatemala' },
  { value: 'America/Guayaquil', label: 'America/Guayaquil' },
  { value: 'America/Guyana', label: 'America/Guyana' },
  { value: 'America/Halifax', label: 'America/Halifax' },
  { value: 'America/Havana', label: 'America/Havana' },
  { value: 'America/Hermosillo', label: 'America/Hermosillo' },
  {
    value: 'America/Indiana/Indianapolis',
    label: 'America/Indiana/Indianapolis',
  },
  { value: 'America/Indiana/Knox', label: 'America/Indiana/Knox' },
  { value: 'America/Indiana/Marengo', label: 'America/Indiana/Marengo' },
  { value: 'America/Indiana/Petersburg', label: 'America/Indiana/Petersburg' },
  { value: 'America/Indiana/Tell_City', label: 'America/Indiana/Tell_City' },
  { value: 'America/Indiana/Vevay', label: 'America/Indiana/Vevay' },
  { value: 'America/Indiana/Vincennes', label: 'America/Indiana/Vincennes' },
  { value: 'America/Indiana/Winamac', label: 'America/Indiana/Winamac' },
  { value: 'America/Indianapolis', label: 'America/Indianapolis' },
  { value: 'America/Inuvik', label: 'America/Inuvik' },
  { value: 'America/Iqaluit', label: 'America/Iqaluit' },
  { value: 'America/Jamaica', label: 'America/Jamaica' },
  { value: 'America/Jujuy', label: 'America/Jujuy' },
  { value: 'America/Juneau', label: 'America/Juneau' },
  {
    value: 'America/Kentucky/Louisville',
    label: 'America/Kentucky/Louisville',
  },
  {
    value: 'America/Kentucky/Monticello',
    label: 'America/Kentucky/Monticello',
  },
  { value: 'America/Knox_IN', label: 'America/Knox_IN' },
  { value: 'America/Kralendijk', label: 'America/Kralendijk' },
  { value: 'America/La_Paz', label: 'America/La_Paz' },
  { value: 'America/Lima', label: 'America/Lima' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles' },
  { value: 'America/Louisville', label: 'America/Louisville' },
  { value: 'America/Lower_Princes', label: 'America/Lower_Princes' },
  { value: 'America/Maceio', label: 'America/Maceio' },
  { value: 'America/Managua', label: 'America/Managua' },
  { value: 'America/Manaus', label: 'America/Manaus' },
  { value: 'America/Marigot', label: 'America/Marigot' },
  { value: 'America/Martinique', label: 'America/Martinique' },
  { value: 'America/Matamoros', label: 'America/Matamoros' },
  { value: 'America/Mazatlan', label: 'America/Mazatlan' },
  { value: 'America/Mendoza', label: 'America/Mendoza' },
  { value: 'America/Menominee', label: 'America/Menominee' },
  { value: 'America/Merida', label: 'America/Merida' },
  { value: 'America/Metlakatla', label: 'America/Metlakatla' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City' },
  { value: 'America/Miquelon', label: 'America/Miquelon' },
  { value: 'America/Moncton', label: 'America/Moncton' },
  { value: 'America/Monterrey', label: 'America/Monterrey' },
  { value: 'America/Montevideo', label: 'America/Montevideo' },
  { value: 'America/Montreal', label: 'America/Montreal' },
  { value: 'America/Montserrat', label: 'America/Montserrat' },
  { value: 'America/Nassau', label: 'America/Nassau' },
  { value: 'America/New_York', label: 'America/New_York' },
  { value: 'America/Nipigon', label: 'America/Nipigon' },
  { value: 'America/Nome', label: 'America/Nome' },
  { value: 'America/Noronha', label: 'America/Noronha' },
  {
    value: 'America/North_Dakota/Beulah',
    label: 'America/North_Dakota/Beulah',
  },
  {
    value: 'America/North_Dakota/Center',
    label: 'America/North_Dakota/Center',
  },
  {
    value: 'America/North_Dakota/New_Salem',
    label: 'America/North_Dakota/New_Salem',
  },
  { value: 'America/Ojinaga', label: 'America/Ojinaga' },
  { value: 'America/Panama', label: 'America/Panama' },
  { value: 'America/Pangnirtung', label: 'America/Pangnirtung' },
  { value: 'America/Paramaribo', label: 'America/Paramaribo' },
  { value: 'America/Phoenix', label: 'America/Phoenix' },
  { value: 'America/Port-au-Prince', label: 'America/Port-au-Prince' },
  { value: 'America/Port_of_Spain', label: 'America/Port_of_Spain' },
  { value: 'America/Porto_Acre', label: 'America/Porto_Acre' },
  { value: 'America/Porto_Velho', label: 'America/Porto_Velho' },
  { value: 'America/Puerto_Rico', label: 'America/Puerto_Rico' },
  { value: 'America/Punta_Arenas', label: 'America/Punta_Arenas' },
  { value: 'America/Rainy_River', label: 'America/Rainy_River' },
  { value: 'America/Rankin_Inlet', label: 'America/Rankin_Inlet' },
  { value: 'America/Recife', label: 'America/Recife' },
  { value: 'America/Regina', label: 'America/Regina' },
  { value: 'America/Resolute', label: 'America/Resolute' },
  { value: 'America/Rio_Branco', label: 'America/Rio_Branco' },
  { value: 'America/Rosario', label: 'America/Rosario' },
  { value: 'America/Santa_Isabel', label: 'America/Santa_Isabel' },
  { value: 'America/Santarem', label: 'America/Santarem' },
  { value: 'America/Santiago', label: 'America/Santiago' },
  { value: 'America/Santo_Domingo', label: 'America/Santo_Domingo' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo' },
  { value: 'America/Scoresbysund', label: 'America/Scoresbysund' },
  { value: 'America/Shiprock', label: 'America/Shiprock' },
  { value: 'America/Sitka', label: 'America/Sitka' },
  { value: 'America/St_Barthelemy', label: 'America/St_Barthelemy' },
  { value: 'America/St_Johns', label: 'America/St_Johns' },
  { value: 'America/St_Kitts', label: 'America/St_Kitts' },
  { value: 'America/St_Lucia', label: 'America/St_Lucia' },
  { value: 'America/St_Thomas', label: 'America/St_Thomas' },
  { value: 'America/St_Vincent', label: 'America/St_Vincent' },
  { value: 'America/Swift_Current', label: 'America/Swift_Current' },
  { value: 'America/Tegucigalpa', label: 'America/Tegucigalpa' },
  { value: 'America/Thule', label: 'America/Thule' },
  { value: 'America/Thunder_Bay', label: 'America/Thunder_Bay' },
  { value: 'America/Tijuana', label: 'America/Tijuana' },
  { value: 'America/Toronto', label: 'America/Toronto' },
  { value: 'America/Tortola', label: 'America/Tortola' },
  { value: 'America/Vancouver', label: 'America/Vancouver' },
  { value: 'America/Virgin', label: 'America/Virgin' },
  { value: 'America/Whitehorse', label: 'America/Whitehorse' },
  { value: 'America/Winnipeg', label: 'America/Winnipeg' },
  { value: 'America/Yakutat', label: 'America/Yakutat' },
  { value: 'America/Yellowknife', label: 'America/Yellowknife' },
  { value: 'Antarctica/Casey', label: 'Antarctica/Casey' },
  { value: 'Antarctica/Davis', label: 'Antarctica/Davis' },
  { value: 'Antarctica/DumontDUrville', label: 'Antarctica/DumontDUrville' },
  { value: 'Antarctica/Macquarie', label: 'Antarctica/Macquarie' },
  { value: 'Antarctica/Mawson', label: 'Antarctica/Mawson' },
  { value: 'Antarctica/McMurdo', label: 'Antarctica/McMurdo' },
  { value: 'Antarctica/Palmer', label: 'Antarctica/Palmer' },
  { value: 'Antarctica/Rothera', label: 'Antarctica/Rothera' },
  { value: 'Antarctica/South_Pole', label: 'Antarctica/South_Pole' },
  { value: 'Antarctica/Syowa', label: 'Antarctica/Syowa' },
  { value: 'Antarctica/Troll', label: 'Antarctica/Troll' },
  { value: 'Antarctica/Vostok', label: 'Antarctica/Vostok' },
  { value: 'Arctic/Longyearbyen', label: 'Arctic/Longyearbyen' },
  { value: 'Asia/Aden', label: 'Asia/Aden' },
  { value: 'Asia/Almaty', label: 'Asia/Almaty' },
  { value: 'Asia/Amman', label: 'Asia/Amman' },
  { value: 'Asia/Anadyr', label: 'Asia/Anadyr' },
  { value: 'Asia/Aqtau', label: 'Asia/Aqtau' },
  { value: 'Asia/Aqtobe', label: 'Asia/Aqtobe' },
  { value: 'Asia/Ashgabat', label: 'Asia/Ashgabat' },
  { value: 'Asia/Ashkhabad', label: 'Asia/Ashkhabad' },
  { value: 'Asia/Atyrau', label: 'Asia/Atyrau' },
  { value: 'Asia/Baghdad', label: 'Asia/Baghdad' },
  { value: 'Asia/Bahrain', label: 'Asia/Bahrain' },
  { value: 'Asia/Baku', label: 'Asia/Baku' },
  { value: 'Asia/Bangkok', label: 'Asia/Bangkok' },
  { value: 'Asia/Barnaul', label: 'Asia/Barnaul' },
  { value: 'Asia/Beirut', label: 'Asia/Beirut' },
  { value: 'Asia/Bishkek', label: 'Asia/Bishkek' },
  { value: 'Asia/Brunei', label: 'Asia/Brunei' },
  { value: 'Asia/Calcutta', label: 'Asia/Calcutta' },
  { value: 'Asia/Chita', label: 'Asia/Chita' },
  { value: 'Asia/Choibalsan', label: 'Asia/Choibalsan' },
  { value: 'Asia/Chongqing', label: 'Asia/Chongqing' },
  { value: 'Asia/Chungking', label: 'Asia/Chungking' },
  { value: 'Asia/Colombo', label: 'Asia/Colombo' },
  { value: 'Asia/Dacca', label: 'Asia/Dacca' },
  { value: 'Asia/Damascus', label: 'Asia/Damascus' },
  { value: 'Asia/Dhaka', label: 'Asia/Dhaka' },
  { value: 'Asia/Dili', label: 'Asia/Dili' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai' },
  { value: 'Asia/Dushanbe', label: 'Asia/Dushanbe' },
  { value: 'Asia/Famagusta', label: 'Asia/Famagusta' },
  { value: 'Asia/Gaza', label: 'Asia/Gaza' },
  { value: 'Asia/Harbin', label: 'Asia/Harbin' },
  { value: 'Asia/Hebron', label: 'Asia/Hebron' },
  { value: 'Asia/Ho_Chi_Minh', label: 'Asia/Ho_Chi_Minh' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong' },
  { value: 'Asia/Hovd', label: 'Asia/Hovd' },
  { value: 'Asia/Irkutsk', label: 'Asia/Irkutsk' },
  { value: 'Asia/Istanbul', label: 'Asia/Istanbul' },
  { value: 'Asia/Jakarta', label: 'Asia/Jakarta' },
  { value: 'Asia/Jayapura', label: 'Asia/Jayapura' },
  { value: 'Asia/Jerusalem', label: 'Asia/Jerusalem' },
  { value: 'Asia/Kabul', label: 'Asia/Kabul' },
  { value: 'Asia/Kamchatka', label: 'Asia/Kamchatka' },
  { value: 'Asia/Karachi', label: 'Asia/Karachi' },
  { value: 'Asia/Kashgar', label: 'Asia/Kashgar' },
  { value: 'Asia/Kathmandu', label: 'Asia/Kathmandu' },
  { value: 'Asia/Katmandu', label: 'Asia/Katmandu' },
  { value: 'Asia/Khandyga', label: 'Asia/Khandyga' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata' },
  { value: 'Asia/Krasnoyarsk', label: 'Asia/Krasnoyarsk' },
  { value: 'Asia/Kuala_Lumpur', label: 'Asia/Kuala_Lumpur' },
  { value: 'Asia/Kuching', label: 'Asia/Kuching' },
  { value: 'Asia/Kuwait', label: 'Asia/Kuwait' },
  { value: 'Asia/Macao', label: 'Asia/Macao' },
  { value: 'Asia/Macau', label: 'Asia/Macau' },
  { value: 'Asia/Magadan', label: 'Asia/Magadan' },
  { value: 'Asia/Makassar', label: 'Asia/Makassar' },
  { value: 'Asia/Manila', label: 'Asia/Manila' },
  { value: 'Asia/Muscat', label: 'Asia/Muscat' },
  { value: 'Asia/Nicosia', label: 'Asia/Nicosia' },
  { value: 'Asia/Novokuznetsk', label: 'Asia/Novokuznetsk' },
  { value: 'Asia/Novosibirsk', label: 'Asia/Novosibirsk' },
  { value: 'Asia/Omsk', label: 'Asia/Omsk' },
  { value: 'Asia/Oral', label: 'Asia/Oral' },
  { value: 'Asia/Phnom_Penh', label: 'Asia/Phnom_Penh' },
  { value: 'Asia/Pontianak', label: 'Asia/Pontianak' },
  { value: 'Asia/Pyongyang', label: 'Asia/Pyongyang' },
  { value: 'Asia/Qatar', label: 'Asia/Qatar' },
  { value: 'Asia/Qyzylorda', label: 'Asia/Qyzylorda' },
  { value: 'Asia/Rangoon', label: 'Asia/Rangoon' },
  { value: 'Asia/Riyadh', label: 'Asia/Riyadh' },
  { value: 'Asia/Saigon', label: 'Asia/Saigon' },
  { value: 'Asia/Sakhalin', label: 'Asia/Sakhalin' },
  { value: 'Asia/Samarkand', label: 'Asia/Samarkand' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore' },
  { value: 'Asia/Srednekolymsk', label: 'Asia/Srednekolymsk' },
  { value: 'Asia/Taipei', label: 'Asia/Taipei' },
  { value: 'Asia/Tashkent', label: 'Asia/Tashkent' },
  { value: 'Asia/Tbilisi', label: 'Asia/Tbilisi' },
  { value: 'Asia/Tehran', label: 'Asia/Tehran' },
  { value: 'Asia/Tel_Aviv', label: 'Asia/Tel_Aviv' },
  { value: 'Asia/Thimbu', label: 'Asia/Thimbu' },
  { value: 'Asia/Thimphu', label: 'Asia/Thimphu' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo' },
  { value: 'Asia/Tomsk', label: 'Asia/Tomsk' },
  { value: 'Asia/Ujung_Pandang', label: 'Asia/Ujung_Pandang' },
  { value: 'Asia/Ulaanbaatar', label: 'Asia/Ulaanbaatar' },
  { value: 'Asia/Ulan_Bator', label: 'Asia/Ulan_Bator' },
  { value: 'Asia/Urumqi', label: 'Asia/Urumqi' },
  { value: 'Asia/Ust-Nera', label: 'Asia/Ust-Nera' },
  { value: 'Asia/Vientiane', label: 'Asia/Vientiane' },
  { value: 'Asia/Vladivostok', label: 'Asia/Vladivostok' },
  { value: 'Asia/Yakutsk', label: 'Asia/Yakutsk' },
  { value: 'Asia/Yangon', label: 'Asia/Yangon' },
  { value: 'Asia/Yekaterinburg', label: 'Asia/Yekaterinburg' },
  { value: 'Asia/Yerevan', label: 'Asia/Yerevan' },
  { value: 'Atlantic/Azores', label: 'Atlantic/Azores' },
  { value: 'Atlantic/Bermuda', label: 'Atlantic/Bermuda' },
  { value: 'Atlantic/Canary', label: 'Atlantic/Canary' },
  { value: 'Atlantic/Cape_Verde', label: 'Atlantic/Cape_Verde' },
  { value: 'Atlantic/Faeroe', label: 'Atlantic/Faeroe' },
  { value: 'Atlantic/Faroe', label: 'Atlantic/Faroe' },
  { value: 'Atlantic/Jan_Mayen', label: 'Atlantic/Jan_Mayen' },
  { value: 'Atlantic/Madeira', label: 'Atlantic/Madeira' },
  { value: 'Atlantic/Reykjavik', label: 'Atlantic/Reykjavik' },
  { value: 'Atlantic/South_Georgia', label: 'Atlantic/South_Georgia' },
  { value: 'Atlantic/St_Helena', label: 'Atlantic/St_Helena' },
  { value: 'Atlantic/Stanley', label: 'Atlantic/Stanley' },
  { value: 'Australia/ACT', label: 'Australia/ACT' },
  { value: 'Australia/Adelaide', label: 'Australia/Adelaide' },
  { value: 'Australia/Brisbane', label: 'Australia/Brisbane' },
  { value: 'Australia/Broken_Hill', label: 'Australia/Broken_Hill' },
  { value: 'Australia/Canberra', label: 'Australia/Canberra' },
  { value: 'Australia/Currie', label: 'Australia/Currie' },
  { value: 'Australia/Darwin', label: 'Australia/Darwin' },
  { value: 'Australia/Eucla', label: 'Australia/Eucla' },
  { value: 'Australia/Hobart', label: 'Australia/Hobart' },
  { value: 'Australia/LHI', label: 'Australia/LHI' },
  { value: 'Australia/Lindeman', label: 'Australia/Lindeman' },
  { value: 'Australia/Lord_Howe', label: 'Australia/Lord_Howe' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne' },
  { value: 'Australia/NSW', label: 'Australia/NSW' },
  { value: 'Australia/North', label: 'Australia/North' },
  { value: 'Australia/Perth', label: 'Australia/Perth' },
  { value: 'Australia/Queensland', label: 'Australia/Queensland' },
  { value: 'Australia/South', label: 'Australia/South' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney' },
  { value: 'Australia/Tasmania', label: 'Australia/Tasmania' },
  { value: 'Australia/Victoria', label: 'Australia/Victoria' },
  { value: 'Australia/West', label: 'Australia/West' },
  { value: 'Australia/Yancowinna', label: 'Australia/Yancowinna' },
  { value: 'Brazil/Acre', label: 'Brazil/Acre' },
  { value: 'Brazil/DeNoronha', label: 'Brazil/DeNoronha' },
  { value: 'Brazil/East', label: 'Brazil/East' },
  { value: 'Brazil/West', label: 'Brazil/West' },
  { value: 'CET', label: 'CET' },
  { value: 'CST6CDT', label: 'CST6CDT' },
  { value: 'Canada/Atlantic', label: 'Canada/Atlantic' },
  { value: 'Canada/Central', label: 'Canada/Central' },
  { value: 'Canada/Eastern', label: 'Canada/Eastern' },
  { value: 'Canada/Mountain', label: 'Canada/Mountain' },
  { value: 'Canada/Newfoundland', label: 'Canada/Newfoundland' },
  { value: 'Canada/Pacific', label: 'Canada/Pacific' },
  { value: 'Canada/Saskatchewan', label: 'Canada/Saskatchewan' },
  { value: 'Canada/Yukon', label: 'Canada/Yukon' },
  { value: 'Chile/Continental', label: 'Chile/Continental' },
  { value: 'Chile/EasterIsland', label: 'Chile/EasterIsland' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'EET', label: 'EET' },
  { value: 'EST', label: 'EST' },
  { value: 'EST5EDT', label: 'EST5EDT' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'Eire', label: 'Eire' },
  { value: 'Etc/GMT', label: 'Etc/GMT' },
  { value: 'Etc/GMT+0', label: 'Etc/GMT+0' },
  { value: 'Etc/GMT+1', label: 'Etc/GMT+1' },
  { value: 'Etc/GMT+10', label: 'Etc/GMT+10' },
  { value: 'Etc/GMT+11', label: 'Etc/GMT+11' },
  { value: 'Etc/GMT+12', label: 'Etc/GMT+12' },
  { value: 'Etc/GMT+2', label: 'Etc/GMT+2' },
  { value: 'Etc/GMT+3', label: 'Etc/GMT+3' },
  { value: 'Etc/GMT+4', label: 'Etc/GMT+4' },
  { value: 'Etc/GMT+5', label: 'Etc/GMT+5' },
  { value: 'Etc/GMT+6', label: 'Etc/GMT+6' },
  { value: 'Etc/GMT+7', label: 'Etc/GMT+7' },
  { value: 'Etc/GMT+8', label: 'Etc/GMT+8' },
  { value: 'Etc/GMT+9', label: 'Etc/GMT+9' },
  { value: 'Etc/GMT-0', label: 'Etc/GMT-0' },
  { value: 'Etc/GMT-1', label: 'Etc/GMT-1' },
  { value: 'Etc/GMT-10', label: 'Etc/GMT-10' },
  { value: 'Etc/GMT-11', label: 'Etc/GMT-11' },
  { value: 'Etc/GMT-12', label: 'Etc/GMT-12' },
  { value: 'Etc/GMT-13', label: 'Etc/GMT-13' },
  { value: 'Etc/GMT-14', label: 'Etc/GMT-14' },
  { value: 'Etc/GMT-2', label: 'Etc/GMT-2' },
  { value: 'Etc/GMT-3', label: 'Etc/GMT-3' },
  { value: 'Etc/GMT-4', label: 'Etc/GMT-4' },
  { value: 'Etc/GMT-5', label: 'Etc/GMT-5' },
  { value: 'Etc/GMT-6', label: 'Etc/GMT-6' },
  { value: 'Etc/GMT-7', label: 'Etc/GMT-7' },
  { value: 'Etc/GMT-8', label: 'Etc/GMT-8' },
  { value: 'Etc/GMT-9', label: 'Etc/GMT-9' },
  { value: 'Etc/GMT0', label: 'Etc/GMT0' },
  { value: 'Etc/Greenwich', label: 'Etc/Greenwich' },
  { value: 'Etc/UCT', label: 'Etc/UCT' },
  { value: 'Etc/UTC', label: 'Etc/UTC' },
  { value: 'Etc/Universal', label: 'Etc/Universal' },
  { value: 'Etc/Zulu', label: 'Etc/Zulu' },
  { value: 'Europe/Amsterdam', label: 'Europe/Amsterdam' },
  { value: 'Europe/Andorra', label: 'Europe/Andorra' },
  { value: 'Europe/Astrakhan', label: 'Europe/Astrakhan' },
  { value: 'Europe/Athens', label: 'Europe/Athens' },
  { value: 'Europe/Belfast', label: 'Europe/Belfast' },
  { value: 'Europe/Belgrade', label: 'Europe/Belgrade' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin' },
  { value: 'Europe/Bratislava', label: 'Europe/Bratislava' },
  { value: 'Europe/Brussels', label: 'Europe/Brussels' },
  { value: 'Europe/Bucharest', label: 'Europe/Bucharest' },
  { value: 'Europe/Budapest', label: 'Europe/Budapest' },
  { value: 'Europe/Busingen', label: 'Europe/Busingen' },
  { value: 'Europe/Chisinau', label: 'Europe/Chisinau' },
  { value: 'Europe/Copenhagen', label: 'Europe/Copenhagen' },
  { value: 'Europe/Dublin', label: 'Europe/Dublin' },
  { value: 'Europe/Gibraltar', label: 'Europe/Gibraltar' },
  { value: 'Europe/Guernsey', label: 'Europe/Guernsey' },
  { value: 'Europe/Helsinki', label: 'Europe/Helsinki' },
  { value: 'Europe/Isle_of_Man', label: 'Europe/Isle_of_Man' },
  { value: 'Europe/Istanbul', label: 'Europe/Istanbul' },
  { value: 'Europe/Jersey', label: 'Europe/Jersey' },
  { value: 'Europe/Kaliningrad', label: 'Europe/Kaliningrad' },
  { value: 'Europe/Kiev', label: 'Europe/Kiev' },
  { value: 'Europe/Kirov', label: 'Europe/Kirov' },
  { value: 'Europe/Lisbon', label: 'Europe/Lisbon' },
  { value: 'Europe/Ljubljana', label: 'Europe/Ljubljana' },
  { value: 'Europe/London', label: 'Europe/London' },
  { value: 'Europe/Luxembourg', label: 'Europe/Luxembourg' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid' },
  { value: 'Europe/Malta', label: 'Europe/Malta' },
  { value: 'Europe/Mariehamn', label: 'Europe/Mariehamn' },
  { value: 'Europe/Minsk', label: 'Europe/Minsk' },
  { value: 'Europe/Monaco', label: 'Europe/Monaco' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow' },
  { value: 'Europe/Nicosia', label: 'Europe/Nicosia' },
  { value: 'Europe/Oslo', label: 'Europe/Oslo' },
  { value: 'Europe/Paris', label: 'Europe/Paris' },
  { value: 'Europe/Podgorica', label: 'Europe/Podgorica' },
  { value: 'Europe/Prague', label: 'Europe/Prague' },
  { value: 'Europe/Riga', label: 'Europe/Riga' },
  { value: 'Europe/Rome', label: 'Europe/Rome' },
  { value: 'Europe/Samara', label: 'Europe/Samara' },
  { value: 'Europe/San_Marino', label: 'Europe/San_Marino' },
  { value: 'Europe/Sarajevo', label: 'Europe/Sarajevo' },
  { value: 'Europe/Saratov', label: 'Europe/Saratov' },
  { value: 'Europe/Simferopol', label: 'Europe/Simferopol' },
  { value: 'Europe/Skopje', label: 'Europe/Skopje' },
  { value: 'Europe/Sofia', label: 'Europe/Sofia' },
  { value: 'Europe/Stockholm', label: 'Europe/Stockholm' },
  { value: 'Europe/Tallinn', label: 'Europe/Tallinn' },
  { value: 'Europe/Tirane', label: 'Europe/Tirane' },
  { value: 'Europe/Tiraspol', label: 'Europe/Tiraspol' },
  { value: 'Europe/Ulyanovsk', label: 'Europe/Ulyanovsk' },
  { value: 'Europe/Uzhgorod', label: 'Europe/Uzhgorod' },
  { value: 'Europe/Vaduz', label: 'Europe/Vaduz' },
  { value: 'Europe/Vatican', label: 'Europe/Vatican' },
  { value: 'Europe/Vienna', label: 'Europe/Vienna' },
  { value: 'Europe/Vilnius', label: 'Europe/Vilnius' },
  { value: 'Europe/Volgograd', label: 'Europe/Volgograd' },
  { value: 'Europe/Warsaw', label: 'Europe/Warsaw' },
  { value: 'Europe/Zagreb', label: 'Europe/Zagreb' },
  { value: 'Europe/Zaporozhye', label: 'Europe/Zaporozhye' },
  { value: 'Europe/Zurich', label: 'Europe/Zurich' },
  { value: 'GB', label: 'GB' },
  { value: 'GB-Eire', label: 'GB-Eire' },
  { value: 'GMT', label: 'GMT' },
  { value: 'GMT+0', label: 'GMT+0' },
  { value: 'GMT-0', label: 'GMT-0' },
  { value: 'GMT0', label: 'GMT0' },
  { value: 'Greenwich', label: 'Greenwich' },
  { value: 'HST', label: 'HST' },
  { value: 'Hongkong', label: 'Hongkong' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'Indian/Antananarivo', label: 'Indian/Antananarivo' },
  { value: 'Indian/Chagos', label: 'Indian/Chagos' },
  { value: 'Indian/Christmas', label: 'Indian/Christmas' },
  { value: 'Indian/Cocos', label: 'Indian/Cocos' },
  { value: 'Indian/Comoro', label: 'Indian/Comoro' },
  { value: 'Indian/Kerguelen', label: 'Indian/Kerguelen' },
  { value: 'Indian/Mahe', label: 'Indian/Mahe' },
  { value: 'Indian/Maldives', label: 'Indian/Maldives' },
  { value: 'Indian/Mauritius', label: 'Indian/Mauritius' },
  { value: 'Indian/Mayotte', label: 'Indian/Mayotte' },
  { value: 'Indian/Reunion', label: 'Indian/Reunion' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Kwajalein', label: 'Kwajalein' },
  { value: 'Libya', label: 'Libya' },
  { value: 'MET', label: 'MET' },
  { value: 'MST', label: 'MST' },
  { value: 'MST7MDT', label: 'MST7MDT' },
  { value: 'Mexico/BajaNorte', label: 'Mexico/BajaNorte' },
  { value: 'Mexico/BajaSur', label: 'Mexico/BajaSur' },
  { value: 'Mexico/General', label: 'Mexico/General' },
  { value: 'NZ', label: 'NZ' },
  { value: 'NZ-CHAT', label: 'NZ-CHAT' },
  { value: 'Navajo', label: 'Navajo' },
  { value: 'PRC', label: 'PRC' },
  { value: 'PST8PDT', label: 'PST8PDT' },
  { value: 'Pacific/Apia', label: 'Pacific/Apia' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland' },
  { value: 'Pacific/Bougainville', label: 'Pacific/Bougainville' },
  { value: 'Pacific/Chatham', label: 'Pacific/Chatham' },
  { value: 'Pacific/Chuuk', label: 'Pacific/Chuuk' },
  { value: 'Pacific/Easter', label: 'Pacific/Easter' },
  { value: 'Pacific/Efate', label: 'Pacific/Efate' },
  { value: 'Pacific/Enderbury', label: 'Pacific/Enderbury' },
  { value: 'Pacific/Fakaofo', label: 'Pacific/Fakaofo' },
  { value: 'Pacific/Fiji', label: 'Pacific/Fiji' },
  { value: 'Pacific/Funafuti', label: 'Pacific/Funafuti' },
  { value: 'Pacific/Galapagos', label: 'Pacific/Galapagos' },
  { value: 'Pacific/Gambier', label: 'Pacific/Gambier' },
  { value: 'Pacific/Guadalcanal', label: 'Pacific/Guadalcanal' },
  { value: 'Pacific/Guam', label: 'Pacific/Guam' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu' },
  { value: 'Pacific/Johnston', label: 'Pacific/Johnston' },
  { value: 'Pacific/Kiritimati', label: 'Pacific/Kiritimati' },
  { value: 'Pacific/Kosrae', label: 'Pacific/Kosrae' },
  { value: 'Pacific/Kwajalein', label: 'Pacific/Kwajalein' },
  { value: 'Pacific/Majuro', label: 'Pacific/Majuro' },
  { value: 'Pacific/Marquesas', label: 'Pacific/Marquesas' },
  { value: 'Pacific/Midway', label: 'Pacific/Midway' },
  { value: 'Pacific/Nauru', label: 'Pacific/Nauru' },
  { value: 'Pacific/Niue', label: 'Pacific/Niue' },
  { value: 'Pacific/Norfolk', label: 'Pacific/Norfolk' },
  { value: 'Pacific/Noumea', label: 'Pacific/Noumea' },
  { value: 'Pacific/Pago_Pago', label: 'Pacific/Pago_Pago' },
  { value: 'Pacific/Palau', label: 'Pacific/Palau' },
  { value: 'Pacific/Pitcairn', label: 'Pacific/Pitcairn' },
  { value: 'Pacific/Pohnpei', label: 'Pacific/Pohnpei' },
  { value: 'Pacific/Ponape', label: 'Pacific/Ponape' },
  { value: 'Pacific/Port_Moresby', label: 'Pacific/Port_Moresby' },
  { value: 'Pacific/Rarotonga', label: 'Pacific/Rarotonga' },
  { value: 'Pacific/Saipan', label: 'Pacific/Saipan' },
  { value: 'Pacific/Samoa', label: 'Pacific/Samoa' },
  { value: 'Pacific/Tahiti', label: 'Pacific/Tahiti' },
  { value: 'Pacific/Tarawa', label: 'Pacific/Tarawa' },
  { value: 'Pacific/Tongatapu', label: 'Pacific/Tongatapu' },
  { value: 'Pacific/Truk', label: 'Pacific/Truk' },
  { value: 'Pacific/Wake', label: 'Pacific/Wake' },
  { value: 'Pacific/Wallis', label: 'Pacific/Wallis' },
  { value: 'Pacific/Yap', label: 'Pacific/Yap' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'ROC', label: 'ROC' },
  { value: 'ROK', label: 'ROK' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'UCT', label: 'UCT' },
  { value: 'US/Alaska', label: 'US/Alaska' },
  { value: 'US/Aleutian', label: 'US/Aleutian' },
  { value: 'US/Arizona', label: 'US/Arizona' },
  { value: 'US/Central', label: 'US/Central' },
  { value: 'US/East-Indiana', label: 'US/East-Indiana' },
  { value: 'US/Eastern', label: 'US/Eastern' },
  { value: 'US/Hawaii', label: 'US/Hawaii' },
  { value: 'US/Indiana-Starke', label: 'US/Indiana-Starke' },
  { value: 'US/Michigan', label: 'US/Michigan' },
  { value: 'US/Mountain', label: 'US/Mountain' },
  { value: 'US/Pacific', label: 'US/Pacific' },
  { value: 'US/Pacific-New', label: 'US/Pacific-New' },
  { value: 'US/Samoa', label: 'US/Samoa' },
  { value: 'UTC', label: 'UTC' },
  { value: 'Universal', label: 'Universal' },
  { value: 'W-SU', label: 'W-SU' },
  { value: 'WET', label: 'WET' },
];
