export const capitalize = (word) => {
  return word[0]?.toUpperCase() + word.slice(1).toLowerCase();
};

// get index for react-select components from value of key
// They array has to have value as one of the keys [{labe:"Some Lable", value:"Some Value"}]

export const getIndex = (myArray, valueOfKey) => {
  const index = myArray.map((object) => object.value).indexOf(valueOfKey);
  return index;
};

// get object for react-select components from value of key
// They array has to have value as one of the keys  [{labe:"Some Lable", value:"Some Value"}]

export const getOption = (myArray, valueOfKey) => {
  return myArray?.find((option) => option?.value === valueOfKey);
};
export const professions = [
  { value: "physician", label: "Physician" },
  { value: "physicianAssistant", label: "Physician Assistant" },
  { value: "nursePractitioner", label: "Nurse Practitioner" },
  { value: "dentist", label: "Dentist" },
  { value: "nurse", label: "Nurse" },
  { value: "pharmacist", label: "Pharmacist" },
  { value: "physicalTherapist", label: "Physical Therapist" },
  { value: "occupationalTherapist", label: "Occupational Therapist" },
  { value: "speechTherapist", label: "Speech Therapist" },
  { value: "respiratoryTherapist", label: "Respiratory Therapist" },
  { value: "dietitian", label: "Dietitian" },
  { value: "socialWorker", label: "Social Worker" },
  { value: "caseManagement", label: "Case Management" },
];

export const subspecialties = [
  { value: "cardiology", label: "Cardiology" },
  { value: "intensivist", label: "Intensivist" },
  { value: "gastroenterologist", label: "Gastroenterologist" },
  { value: "dermatologist", label: "Dermatologist" },
  { value: "neurologist", label: "Neurologist" },
  { value: "hematologist", label: "Hematologist" },
  { value: "endodontist", label: "Endodontist" },
  { value: "orthodontist", label: "Orthodontist" },
];

// length 164
export const currencylist = [
  { label: "Afghan Afghani", value: "AFA", symbol: "؋" },
  { label: "Albanian Lek", value: "ALL", symbol: "Lek" },
  { label: "Algerian Dinar", value: "DZD", symbol: "دج" },
  { label: "Angolan Kwanza", value: "AOA", symbol: "Kz" },
  { label: "Argentine Peso", value: "ARS", symbol: "$" },
  { label: "Armenian Dram", value: "AMD", symbol: "֏" },
  { label: "Aruban Florin", value: "AWG", symbol: "ƒ" },
  { label: "Australian Dollar", value: "AUD", symbol: "$" },
  { label: "Azerbaijani Manat", value: "AZN", symbol: "m" },
  { label: "Bahamian Dollar", value: "BSD", symbol: "B$" },
  { label: "Bahraini Dinar", value: "BHD", symbol: ".د.ب" },
  { label: "Bangladeshi Taka", value: "BDT", symbol: "৳" },
  { label: "Barbadian Dollar", value: "BBD", symbol: "Bds$" },
  { label: "Belarusian Ruble", value: "BYR", symbol: "Br" },
  { label: "Belgian Franc", value: "BEF", symbol: "fr" },
  { label: "Belize Dollar", value: "BZD", symbol: "$" },
  { label: "Bermudan Dollar", value: "BMD", symbol: "$" },
  { label: "Bhutanese Ngultrum", value: "BTN", symbol: "Nu." },
  { label: "Bitcoin", value: "BTC", symbol: "฿" },
  { label: "Bolivian Boliviano", value: "BOB", symbol: "Bs." },
  {
    label: "Bosnia-Herzegovina Convertible Mark",
    value: "BAM",
    symbol: "KM",
  },
  { label: "Botswanan Pula", value: "BWP", symbol: "P" },
  { label: "Brazilian Real", value: "BRL", symbol: "R$" },
  { label: "British Pound Sterling", value: "GBP", symbol: "£" },
  { label: "Brunei Dollar", value: "BND", symbol: "B$" },
  { label: "Bulgarian Lev", value: "BGN", symbol: "Лв." },
  { label: "Burundian Franc", value: "BIF", symbol: "FBu" },
  { label: "Cambodian Riel", value: "KHR", symbol: "KHR" },
  { label: "Canadian Dollar", value: "CAD", symbol: "$" },
  { label: "Cape Verdean Escudo", value: "CVE", symbol: "$" },
  { label: "Cayman Islands Dollar", value: "KYD", symbol: "$" },
  { label: "CFA Franc BCEAO", value: "XOF", symbol: "CFA" },
  { label: "CFA Franc BEAC", value: "XAF", symbol: "FCFA" },
  { label: "CFP Franc", value: "XPF", symbol: "₣" },
  { label: "Chilean Peso", value: "CLP", symbol: "$" },
  { label: "Chinese Yuan", value: "CNY", symbol: "¥" },
  { label: "Colombian Peso", value: "COP", symbol: "$" },
  { label: "Comorian Franc", value: "KMF", symbol: "CF" },
  { label: "Congolese Franc", value: "CDF", symbol: "FC" },
  { label: "Costa Rican ColÃ³n", value: "CRC", symbol: "₡" },
  { label: "Croatian Kuna", value: "HRK", symbol: "kn" },
  { label: "Cuban Convertible Peso", value: "CUC", symbol: "$, CUC" },
  { label: "Czech Republic Koruna", value: "CZK", symbol: "Kč" },
  { label: "Danish Krone", value: "DKK", symbol: "Kr." },
  { label: "Djiboutian Franc", value: "DJF", symbol: "Fdj" },
  { label: "Dominican Peso", value: "DOP", symbol: "$" },
  { label: "East Caribbean Dollar", value: "XCD", symbol: "$" },
  { label: "Egyptian Pound", value: "EGP", symbol: "ج.م" },
  { label: "Eritrean Nakfa", value: "ERN", symbol: "Nfk" },
  { label: "Estonian Kroon", value: "EEK", symbol: "kr" },
  { label: "Ethiopian Birr", value: "ETB", symbol: "Nkf" },
  { label: "Euro", value: "EUR", symbol: "€" },
  { label: "Falkland Islands Pound", value: "FKP", symbol: "£" },
  { label: "Fijian Dollar", value: "FJD", symbol: "FJ$" },
  { label: "Gambian Dalasi", value: "GMD", symbol: "D" },
  { label: "Georgian Lari", value: "GEL", symbol: "ლ" },
  { label: "German Mark", value: "DEM", symbol: "DM" },
  { label: "Ghanaian Cedi", value: "GHS", symbol: "GH₵" },
  { label: "Gibraltar Pound", value: "GIP", symbol: "£" },
  { label: "Greek Drachma", value: "GRD", symbol: "₯, Δρχ, Δρ" },
  { label: "Guatemalan Quetzal", value: "GTQ", symbol: "Q" },
  { label: "Guinean Franc", value: "GNF", symbol: "FG" },
  { label: "Guyanaese Dollar", value: "GYD", symbol: "$" },
  { label: "Haitian Gourde", value: "HTG", symbol: "G" },
  { label: "Honduran Lempira", value: "HNL", symbol: "L" },
  { label: "Hong Kong Dollar", value: "HKD", symbol: "$" },
  { label: "Hungarian Forint", value: "HUF", symbol: "Ft" },
  { label: "Icelandic KrÃ³na", value: "ISK", symbol: "kr" },
  { label: "Indian Rupee - INR (₹) ", value: "INR", symbol: "₹" },
  { label: "Indonesian Rupiah", value: "IDR", symbol: "Rp" },
  { label: "Iranian Rial", value: "IRR", symbol: "﷼" },
  { label: "Iraqi Dinar", value: "IQD", symbol: "د.ع" },
  { label: "Israeli New Sheqel", value: "ILS", symbol: "₪" },
  { label: "Italian Lira", value: "ITL", symbol: "L,£" },
  { label: "Jamaican Dollar", value: "JMD", symbol: "J$" },
  { label: "Japanese Yen", value: "JPY", symbol: "¥" },
  { label: "Jordanian Dinar", value: "JOD", symbol: "ا.د" },
  { label: "Kazakhstani Tenge", value: "KZT", symbol: "лв" },
  { label: "Kenyan Shilling", value: "KES", symbol: "KSh" },
  { label: "Kuwaiti Dinar", value: "KWD", symbol: "ك.د" },
  { label: "Kyrgystani Som", value: "KGS", symbol: "лв" },
  { label: "Laotian Kip", value: "LAK", symbol: "₭" },
  { label: "Latvian Lats", value: "LVL", symbol: "Ls" },
  { label: "Lebanese Pound", value: "LBP", symbol: "£" },
  { label: "Lesotho Loti", value: "LSL", symbol: "L" },
  { label: "Liberian Dollar", value: "LRD", symbol: "$" },
  { label: "Libyan Dinar", value: "LYD", symbol: "د.ل" },
  { label: "Lithuanian Litas", value: "LTL", symbol: "Lt" },
  { label: "Macanese Pataca", value: "MOP", symbol: "$" },
  { label: "Macedonian Denar", value: "MKD", symbol: "ден" },
  { label: "Malagasy Ariary", value: "MGA", symbol: "Ar" },
  { label: "Malawian Kwacha", value: "MWK", symbol: "MK" },
  { label: "Malaysian Ringgit", value: "MYR", symbol: "RM" },
  { label: "Maldivian Rufiyaa", value: "MVR", symbol: "Rf" },
  { label: "Mauritanian Ouguiya", value: "MRO", symbol: "MRU" },
  { label: "Mauritian Rupee", value: "MUR", symbol: "₨" },
  { label: "Mexican Peso", value: "MXN", symbol: "$" },
  { label: "Moldovan Leu", value: "MDL", symbol: "L" },
  { label: "Mongolian Tugrik", value: "MNT", symbol: "₮" },
  { label: "Moroccan Dirham", value: "MAD", symbol: "MAD" },
  { label: "Mozambican Metical", value: "MZM", symbol: "MT" },
  { label: "Myanmar Kyat", value: "MMK", symbol: "K" },
  { label: "Namibian Dollar", value: "NAD", symbol: "$" },
  { label: "Nepalese Rupee", value: "NPR", symbol: "₨" },
  {
    label: "Netherlands Antillean Guilder",
    value: "ANG",
    symbol: "ƒ",
  },
  { label: "New Taiwan Dollar", value: "TWD", symbol: "$" },
  { label: "New Zealand Dollar", value: "NZD", symbol: "$" },
  { label: "Nicaraguan CÃ³rdoba", value: "NIO", symbol: "C$" },
  { label: "Nigerian Naira", value: "NGN", symbol: "₦" },
  { label: "North Korean Won", value: "KPW", symbol: "₩" },
  { label: "Norwegian Krone", value: "NOK", symbol: "kr" },
  { label: "Omani Rial", value: "OMR", symbol: ".ع.ر" },
  { label: "Pakistani Rupee", value: "PKR", symbol: "₨" },
  { label: "Panamanian Balboa", value: "PAB", symbol: "B/." },
  { label: "Papua New Guinean Kina", value: "PGK", symbol: "K" },
  { label: "Paraguayan Guarani", value: "PYG", symbol: "₲" },
  { label: "Peruvian Nuevo Sol", value: "PEN", symbol: "S/." },
  { label: "Philippine Peso", value: "PHP", symbol: "₱" },
  { label: "Polish Zloty", value: "PLN", symbol: "zł" },
  { label: "Qatari Rial", value: "QAR", symbol: "ق.ر" },
  { label: "Romanian Leu", value: "RON", symbol: "lei" },
  { label: "Russian Ruble", value: "RUB", symbol: "₽" },
  { label: "Rwandan Franc", value: "RWF", symbol: "FRw" },
  { label: "Salvadoran ColÃ³n", value: "SVC", symbol: "₡" },
  { label: "Samoan Tala", value: "WST", symbol: "SAT" },
  { label: "Saudi Riyal", value: "SAR", symbol: "﷼" },
  { label: "Serbian Dinar", value: "RSD", symbol: "din" },
  { label: "Seychellois Rupee", value: "SCR", symbol: "SRe" },
  { label: "Sierra Leonean Leone", value: "SLL", symbol: "Le" },
  { label: "Singapore Dollar", value: "SGD", symbol: "$" },
  { label: "Slovak Koruna", value: "SKK", symbol: "Sk" },
  { label: "Solomon Islands Dollar", value: "SBD", symbol: "Si$" },
  { label: "Somali Shilling", value: "SOS", symbol: "Sh.so." },
  { label: "South African Rand", value: "ZAR", symbol: "R" },
  { label: "South Korean Won", value: "KRW", symbol: "₩" },
  { label: "Special Drawing Rights", value: "XDR", symbol: "SDR" },
  { label: "Sri Lankan Rupee", value: "LKR", symbol: "Rs" },
  { label: "St. Helena Pound", value: "SHP", symbol: "£" },
  { label: "Sudanese Pound", value: "SDG", symbol: ".س.ج" },
  { label: "Surinamese Dollar", value: "SRD", symbol: "$" },
  { label: "Swazi Lilangeni", value: "SZL", symbol: "E" },
  { label: "Swedish Krona", value: "SEK", symbol: "kr" },
  { label: "Swiss Franc", value: "CHF", symbol: "CHf" },
  { label: "Syrian Pound", value: "SYP", symbol: "LS" },
  { label: "São Tomé and Príncipe Dobra", value: "STD", symbol: "Db" },
  { label: "Tajikistani Somoni", value: "TJS", symbol: "SM" },
  { label: "Tanzanian Shilling", value: "TZS", symbol: "TSh" },
  { label: "Thai Baht", value: "THB", symbol: "฿" },
  { label: "Tongan Pa'anga", value: "TOP", symbol: "$" },
  { label: "Trinidad & Tobago Dollar", value: "TTD", symbol: "$" },
  { label: "Tunisian Dinar", value: "TND", symbol: "ت.د" },
  { label: "Turkish Lira", value: "TRY", symbol: "₺" },
  { label: "Turkmenistani Manat", value: "TMT", symbol: "T" },
  { label: "Ugandan Shilling", value: "UGX", symbol: "USh" },
  { label: "Ukrainian Hryvnia", value: "UAH", symbol: "₴" },
  {
    label: "United Arab Emirates Dirham",
    value: "AED",
    symbol: "إ.د",
  },
  { label: "Uruguayan Peso", value: "UYU", symbol: "$" },
  { label: "US Dollar", value: "USD", symbol: "$" },
  { label: "Uzbekistan Som", value: "UZS", symbol: "лв" },
  { label: "Vanuatu Vatu", value: "VUV", symbol: "VT" },
  { label: "Venezuelan BolÃvar", value: "VEF", symbol: "Bs" },
  { label: "Vietnamese Dong", value: "VND", symbol: "₫" },
  { label: "Yemeni Rial", value: "YER", symbol: "﷼" },
  { label: "Zambian Kwacha", value: "ZMK", symbol: "ZK" },
];

export const timezones = [
  {
    value: "(UTC-12:00) International Date Line West",
    label: "(UTC-12:00) International Date Line West",
  },
  {
    value: "(UTC-11:00) Coordinated Universal Time-11",
    label: "(UTC-11:00) Coordinated Universal Time-11",
  },
  { value: "(UTC-10:00) Hawaii", label: "(UTC-10:00) Hawaii" },
  { value: "(UTC-09:00) Alaska", label: "(UTC-09:00) Alaska" },
  {
    value: "(UTC-08:00) Baja California",
    label: "(UTC-08:00) Baja California",
  },
  {
    value: "(UTC-08:00) Pacific Time (US and Canada)",
    label: "(UTC-08:00) Pacific Time (US and Canada)",
  },
  {
    value: "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
    label: "(UTC-07:00) Chihuahua, La Paz, Mazatlan",
  },
  { value: "(UTC-07:00) Arizona", label: "(UTC-07:00) Arizona" },
  {
    value: "(UTC-07:00) Mountain Time (US and Canada)",
    label: "(UTC-07:00) Mountain Time (US and Canada)",
  },
  {
    value: "(UTC-06:00) Central America",
    label: "(UTC-06:00) Central America",
  },
  {
    value: "(UTC-06:00) Central Time (US and Canada)",
    label: "(UTC-06:00) Central Time (US and Canada)",
  },
  { value: "(UTC-06:00) Saskatchewan", label: "(UTC-06:00) Saskatchewan" },
  {
    value: "(UTC-06:00) Guadalajara, Mexico City, Monterey",
    label: "(UTC-06:00) Guadalajara, Mexico City, Monterey",
  },
  {
    value: "(UTC-05:00) Bogota, Lima, Quito",
    label: "(UTC-05:00) Bogota, Lima, Quito",
  },
  {
    value: "(UTC-05:00) Indiana (East)",
    label: "(UTC-05:00) Indiana (East)",
  },
  {
    value: "(UTC-05:00) Eastern Time (US and Canada)",
    label: "(UTC-05:00) Eastern Time (US and Canada)",
  },
  { value: "(UTC-04:30) Caracas", label: "(UTC-04:30) Caracas" },
  {
    value: "(UTC-04:00) Atlantic Time (Canada)",
    label: "(UTC-04:00) Atlantic Time (Canada)",
  },
  { value: "(UTC-04:00) Asuncion", label: "(UTC-04:00) Asuncion" },
  {
    value: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
    label: "(UTC-04:00) Georgetown, La Paz, Manaus, San Juan",
  },
  { value: "(UTC-04:00) Cuiaba", label: "(UTC-04:00) Cuiaba" },
  { value: "(UTC-04:00) Santiago", label: "(UTC-04:00) Santiago" },
  { value: "(UTC-03:30) Newfoundland", label: "(UTC-03:30) Newfoundland" },
  { value: "(UTC-03:00) Brasilia", label: "(UTC-03:00) Brasilia" },
  { value: "(UTC-03:00) Greenland", label: "(UTC-03:00) Greenland" },
  {
    value: "(UTC-03:00) Cayenne, Fortaleza",
    label: "(UTC-03:00) Cayenne, Fortaleza",
  },
  { value: "(UTC-03:00) Buenos Aires", label: "(UTC-03:00) Buenos Aires" },
  { value: "(UTC-03:00) Montevideo", label: "(UTC-03:00) Montevideo" },
  {
    value: "(UTC-02:00) Coordinated Universal Time-2",
    label: "(UTC-02:00) Coordinated Universal Time-2",
  },
  { value: "(UTC-01:00) Cape Verde", label: "(UTC-01:00) Cape Verde" },
  { value: "(UTC-01:00) Azores", label: "(UTC-01:00) Azores" },
  { value: "(UTC+00:00) Casablanca", label: "(UTC+00:00) Casablanca" },
  {
    value: "(UTC+00:00) Monrovia, Reykjavik",
    label: "(UTC+00:00) Monrovia, Reykjavik",
  },
  {
    value: "(UTC+00:00) Dublin, Edinburgh, Lisbon, London",
    label: "(UTC+00:00) Dublin, Edinburgh, Lisbon, London",
  },
  {
    value: "(UTC+00:00) Coordinated Universal Time",
    label: "(UTC+00:00) Coordinated Universal Time",
  },
  {
    value: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    label: "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  },
  {
    value: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
    label: "(UTC+01:00) Brussels, Copenhagen, Madrid, Paris",
  },
  {
    value: "(UTC+01:00) West Central Africa",
    label: "(UTC+01:00) West Central Africa",
  },
  {
    value: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    label: "(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  },
  {
    value: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
    label: "(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
  },
  { value: "(UTC+01:00) Windhoek", label: "(UTC+01:00) Windhoek" },
  {
    value: "(UTC+02:00) Athens, Bucharest, Istanbul",
    label: "(UTC+02:00) Athens, Bucharest, Istanbul",
  },
  {
    value: "(UTC+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
    label: "(UTC+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius",
  },
  { value: "(UTC+02:00) Cairo", label: "(UTC+02:00) Cairo" },
  { value: "(UTC+02:00) Damascus", label: "(UTC+02:00) Damascus" },
  { value: "(UTC+02:00) Amman", label: "(UTC+02:00) Amman" },
  {
    value: "(UTC+02:00) Harare, Pretoria",
    label: "(UTC+02:00) Harare, Pretoria",
  },
  { value: "(UTC+02:00) Jerusalem", label: "(UTC+02:00) Jerusalem" },
  { value: "(UTC+02:00) Beirut", label: "(UTC+02:00) Beirut" },
  { value: "(UTC+03:00) Baghdad", label: "(UTC+03:00) Baghdad" },
  { value: "(UTC+03:00) Minsk", label: "(UTC+03:00) Minsk" },
  {
    value: "(UTC+03:00) Kuwait, Riyadh",
    label: "(UTC+03:00) Kuwait, Riyadh",
  },
  { value: "(UTC+03:00) Nairobi", label: "(UTC+03:00) Nairobi" },
  { value: "(UTC+03:30) Tehran", label: "(UTC+03:30) Tehran" },
  {
    value: "(UTC+04:00) Moscow, St. Petersburg, Volgograd",
    label: "(UTC+04:00) Moscow, St. Petersburg, Volgograd",
  },
  { value: "(UTC+04:00) Tbilisi", label: "(UTC+04:00) Tbilisi" },
  { value: "(UTC+04:00) Yerevan", label: "(UTC+04:00) Yerevan" },
  {
    value: "(UTC+04:00) Abu Dhabi, Muscat",
    label: "(UTC+04:00) Abu Dhabi, Muscat",
  },
  { value: "(UTC+04:00) Baku", label: "(UTC+04:00) Baku" },
  { value: "(UTC+04:00) Port Louis", label: "(UTC+04:00) Port Louis" },
  { value: "(UTC+04:30) Kabul", label: "(UTC+04:30) Kabul" },
  { value: "(UTC+05:00) Tashkent", label: "(UTC+05:00) Tashkent" },
  {
    value: "(UTC+05:00) Islamabad, Karachi",
    label: "(UTC+05:00) Islamabad, Karachi",
  },
  {
    value: "(UTC+05:30) Sri Jayewardenepura Kotte",
    label: "(UTC+05:30) Sri Jayewardenepura Kotte",
  },
  {
    value: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
    label: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi",
  },
  { value: "(UTC+05:45) Kathmandu", label: "(UTC+05:45) Kathmandu" },
  { value: "(UTC+06:00) Astana", label: "(UTC+06:00) Astana" },
  { value: "(UTC+06:00) Dhaka", label: "(UTC+06:00) Dhaka" },
  { value: "(UTC+06:00) Yekaterinburg", label: "(UTC+06:00) Yekaterinburg" },
  { value: "(UTC+06:30) Yangon", label: "(UTC+06:30) Yangon" },
  {
    value: "(UTC+07:00) Bangkok, Hanoi, Jakarta",
    label: "(UTC+07:00) Bangkok, Hanoi, Jakarta",
  },
  { value: "(UTC+07:00) Novosibirsk", label: "(UTC+07:00) Novosibirsk" },
  { value: "(UTC+08:00) Krasnoyarsk", label: "(UTC+08:00) Krasnoyarsk" },
  { value: "(UTC+08:00) Ulaanbaatar", label: "(UTC+08:00) Ulaanbaatar" },
  {
    value: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
    label: "(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
  },
  { value: "(UTC+08:00) Perth", label: "(UTC+08:00) Perth" },
  {
    value: "(UTC+08:00) Kuala Lumpur, Singapore",
    label: "(UTC+08:00) Kuala Lumpur, Singapore",
  },
  { value: "(UTC+08:00) Taipei", label: "(UTC+08:00) Taipei" },
  { value: "(UTC+09:00) Irkutsk", label: "(UTC+09:00) Irkutsk" },
  { value: "(UTC+09:00) Seoul", label: "(UTC+09:00) Seoul" },
  {
    value: "(UTC+09:00) Osaka, Sapporo, Tokyo",
    label: "(UTC+09:00) Osaka, Sapporo, Tokyo",
  },
  { value: "(UTC+09:30) Darwin", label: "(UTC+09:30) Darwin" },
  { value: "(UTC+09:30) Adelaide", label: "(UTC+09:30) Adelaide" },
  { value: "(UTC+10:00) Hobart", label: "(UTC+10:00) Hobart" },
  { value: "(UTC+10:00) Yakutsk", label: "(UTC+10:00) Yakutsk" },
  { value: "(UTC+10:00) Brisbane", label: "(UTC+10:00) Brisbane" },
  {
    value: "(UTC+10:00) Guam, Port Moresby",
    label: "(UTC+10:00) Guam, Port Moresby",
  },
  {
    value: "(UTC+10:00) Canberra, Melbourne, Sydney",
    label: "(UTC+10:00) Canberra, Melbourne, Sydney",
  },
  { value: "(UTC+11:00) Vladivostok", label: "(UTC+11:00) Vladivostok" },
  {
    value: "(UTC+11:00) Solomon Islands, New Caledonia",
    label: "(UTC+11:00) Solomon Islands, New Caledonia",
  },
  {
    value: "(UTC+12:00) Coordinated Universal Time+12",
    label: "(UTC+12:00) Coordinated Universal Time+12",
  },
  {
    value: "(UTC+12:00) Fiji, Marshall Islands",
    label: "(UTC+12:00) Fiji, Marshall Islands",
  },
  { value: "(UTC+12:00) Magadan", label: "(UTC+12:00) Magadan" },
  {
    value: "(UTC+12:00) Auckland, Wellington",
    label: "(UTC+12:00) Auckland, Wellington",
  },
  { value: "(UTC+13:00) Nuku'alofa", label: "(UTC+13:00) Nuku'alofa" },
  { value: "(UTC+13:00) Samoa", label: "(UTC+13:00) Samoa" },
];
