export const USER_PROFILE_LOADED = "USER_PROFILE_LOADED";
export const GET_USER_EXTERNAL_CREDITS = "GET_USER_EXTERNAL_CREDITS";
export const GET_USER_SINGELE_EXTERNAL_CREDIT =
  "GET_USER_SINGELE_EXTERNAL_CREDIT";
export const CLEAR_USER_SINGELE_EXTERNAL_CREDIT =
  "CLEAR_USER_SINGELE_EXTERNAL_CREDIT";
export const GET_USER_CREDIT_CONFERENCES = "GET_USER_CREDIT_CONFERENCES";
